#%RAML 1.0 NamedExample

value:
-
  ID: 1
  jmbg: "1405669993636"
  name: Janko
  surname: Jankovic
  citizenship: Srbija
  symptoms: no
  homeIsolation: 1
  dateEnd?:
  isolationDays: 14
-
  ID: 2
  jmbg: 1405669998636"
  name: Petar
  surname: Petrovic
  citizenship: Srbija
  symptoms: no
  homeIsolation: 1
  dateEnd?:
  isolationDays: 28
 