http:
  port: "8081"
db:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"
  database: "coronavirusdb"
email :
  host: "smtp.gmail.com"   
  port: "587"
  user: "andriceva997@gmail.com"
 